- name: update cache
  ansible.builtin.yum:
    update_cache: yes

- name: reinstall pip3
  become: true
  ansible.builtin.yum:
    name: python3-pip
    state: latest

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2024011407424253630000000b.c5szxeahybda.us-east-1.rds.amazonaws.com" 
    login_user: "cloudnloud"
    login_password: "12345645578"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^localhost', replace: "terraform-2024011407424253630000000b.c5szxeahybda.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', replace: "cloudnloud" }
    - { regexp: '^database_name_here', replace: "ordpressdwb" }
    - { regexp: '^password_here', replace: "12345645578" }
